name: Build_SkyStream_TX_Linux
on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libasound2-dev libjack-jackd2-dev libfreetype6-dev \
            libx11-dev libxcomposite-dev libxcursor-dev libxinerama-dev \
            libxext-dev libxrandr-dev libcurl4-openssl-dev pkg-config \
            freeglut3-dev libgtk-3-dev libwebkit2gtk-4.1-dev ninja-build

      - name: Build
        run: |
          rm -rf build
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
          cmake --build build --target SkyStream_TX --config Release

      - name: Find and Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: SkyStream-TX-Linux-Binary
          path: |
            build/**/SkyStream_TX